<GridButton>:
    source: 'img/tile_full.png'
    on_press: self.parent.on_click(self)
    size_hint: None, None
    size: 32, 32

    canvas:
        Color:
            rgb: app.foreground_color
        Rectangle:
            texture: self.texture
            pos: self.pos
            size: self.size

<Grid>:
    canvas.before:
        Color:
            rgb: app.background_color
        Rectangle:
            pos: self.pos
            size: self.size
